### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by FeygelsonE** [FeygelsonE/ezStay#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Update your wiki with the live link to the app so I can verify the progress, assign the issue back to me when this is done.

**Comment by AAlfarho** [comment]
There are a couple of things missing from this MVP before I can sign it off.

# Functionality
- [x] Your logo, in this case, your h3 'ezStay logo' should redirect (on click) you to / or your splash. As of now it is only text.
- [x] Handle cases when users try to access routes that do not exist, https://ezstay.herokuapp.com/#/this-does-not-exist should redirect you to / or /login /singup etc..
- [x] Errors are not clearing up, try invalid credentials, go to `/#/` try to log in again, the error message persist, they should not. Same behavior if we transition from signup to login.
- [x] There is no demo login, we should be able to login as a default user, that way we dont need to create an account to get the full experience of your site.
- [x] If you will proceed with _modals_ in your signup/login form there should be a way of closing them, you should be able to close them hiting `esc` or clicking the dimmed area.

# Styling
- [x] This MVP will also cover your landing page, add adequate styling.
- [x] The font-size on the inputs is not the same size as the placeholders. Font size when typing in the inputs is too small.
- [x] Add a reset css file.
- [x] Your errors ar not centered, also, the red background its to hard on the eyes. If you want to go with the red, consider setting a less bright red directly to the font color.
- [x] Consider setting a radius border to your forms, like what you did to the buttons.
- [x] Consider setting your logo at the top of your forms, this will take part of the vertical space that is not being used in the forms.

**Comment by AAlfarho** [comment]
Assign this issue back to me when the updates are pushed to heroku.

**Comment by FeygelsonE** [comment]
Finished

**Comment by AAlfarho** [comment]
Great job with the update, a couple of details we need to address before moving on to the next mvp.

## Functionality
- [x] When closing the _modal_ for signup or login, an unnecessary refresh is being triggered, update your `<a className="close-button" href="/">...` href to a `<Link>` or consider pushing  to history or replacing the location, that way we won't reload the whole website.
- [x] Remove console.log statements.
- [x] There is a warning message in a component `Warning: Invalid DOM property 'class'`, check if any JSX component has `class`, rather than `className`.

## Style
- [x] On the login/signup modal, set some vertical space between the closing icon, and the input field.
- [x] (Optional) Take a look at the following snap, it reduces the logo and changes a couple pixels the padding of the ezStay logo and centers the component a little more. Consider following something similar. 
![screen shot 2018-02-02 at 11 41 21 am](https://user-images.githubusercontent.com/1103663/35751682-390dd43a-080e-11e8-853f-0865f43babc2.png)

**Comment by FeygelsonE** [comment]
All done. The "Warning: Invalid DOM property 'class'" is because of the icon I'm importing from font-awesome I believe.

**Comment by AAlfarho** [comment]
To get rid of that error update `<i class="fas fa-home fa-3x"></i>` to `<i className="fas fa-home fa-3x"></i>`.

The current state of the app completes this MVP.
